# Aljabar

### Pengertian :  
Aljabar

In [1]:
import numpy as np
#Membuat matriks
A = np.array([[1, 2, 3],[3, 4, 5],[5, 6, 7]])
B = np.array([[4, 5, 6],[8, 3, 7],[2, 9, 1]])
C = np.array([[5, 4, 9],[5, 1, 2]])
D = np.array([[1, 7, 4],[1, 3, 5],[7, 8, 9]])

print(A)
print(B)
print(C)
print(D)
#untuk mengetahui ukuran matriks
C.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[4 5 6]
 [8 3 7]
 [2 9 1]]
[[5 4 9]
 [5 1 2]]
[[1 7 4]
 [1 3 5]
 [7 8 9]]


(2, 3)

In [ ]:
#Operasi2 Matriks
c = 2
d = 4
G = (c+d)*A
H = (c*A)+(d*A)
print(G)
print(H)

In [ ]:
#Matriks Transpose
C_T = C.transpose()
Cov = C@C_T
print(C)
print(C_T)
print(Cov)
Cov.shape

In [ ]:
#membuat matriik
A = np.random.randint(10,size=(3,3))
print(A)